name: Bug report
description: Report a problem with a skill or repo setup
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include the exact error message and what you were trying to do.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output (e.g., `codex features list`, startup modal, stack traces).
      render: shell
  - type: input
    id: codex-version
    attributes:
      label: Codex version
      placeholder: Paste output of `codex --version`
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Windows / macOS / Linux

